"""create sensor readings table

Revision ID: 38c983758c9a
Revises: e2ec11351944
Create Date: 2026-08-07 13:58:32.469205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38c983758c9a"
down_revision: str | Sequence[str] | None = "e2ec11351944"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_readings",
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensor_readings_recorded_at"), "sensor_readings", ["recorded_at"], unique=False
    )
    op.create_index(
        op.f("ix_sensor_readings_sensor_id"), "sensor_readings", ["sensor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sensor_readings_sensor_id"), table_name="sensor_readings")
    op.drop_index(op.f("ix_sensor_readings_recorded_at"), table_name="sensor_readings")
    op.drop_table("sensor_readings")
    # ### end Alembic commands ###
