"""create alerts table

Revision ID: c89d9c294217
Revises: 38c983758c9a
Create Date: 2026-08-10 16:17:09.273082

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c89d9c294217"
down_revision: str | Sequence[str] | None = "38c983758c9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column(
            "severity", sa.Enum("WARNING", "CRITICAL", name="alert_severity"), nullable=False
        ),
        sa.Column("status", sa.Enum("ACTIVE", "RESOLVED", name="alert_status"), nullable=False),
        sa.Column("alert_type", sa.String(length=100), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_machine_id"), "alerts", ["machine_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_machine_id"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
