"""create machines table

Revision ID: d9ba0acd7be7
Revises: a37096d55a4d
Create Date: 2026-07-31 00:37:05.617694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9ba0acd7be7"
down_revision: str | Sequence[str] | None = "a37096d55a4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machines",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model_number", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "IDLE", "MAINTENANCE", "OFFLINE", name="machine_status"),
            nullable=False,
        ),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("production_line_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["production_line_id"], ["production_lines.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_machines_production_line_id"), "machines", ["production_line_id"], unique=False
    )
    op.create_index(op.f("ix_machines_serial_number"), "machines", ["serial_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_machines_serial_number"), table_name="machines")
    op.drop_index(op.f("ix_machines_production_line_id"), table_name="machines")
    op.drop_table("machines")
    # ### end Alembic commands ###
