"""create sensors table

Revision ID: e2ec11351944
Revises: d9ba0acd7be7
Create Date: 2026-08-07 13:47:12.214372

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2ec11351944"
down_revision: str | Sequence[str] | None = "d9ba0acd7be7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "sensor_type",
            sa.Enum("TEMPERATURE", "PRESSURE", "VIBRATION", "RPM", "ENERGY", name="sensor_type"),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sensors_machine_id"), "sensors", ["machine_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sensors_machine_id"), table_name="sensors")
    op.drop_table("sensors")
    # ### end Alembic commands ###
